//modal code from boostrap. will implement vue later
const myModal = document.getElementById('myModal')
const myInput = document.getElementById('myInput')

// myModal.addEventListener('shown.bs.modal', () => {
//   myInput.focus()
// })


const app = Vue.createApp({
  created() { 
    fetch('zeronis.json').then(rep => rep.json()).then(json => {
      this.zeroniIcons = json;
    }),
      fetch('skills.json').then(a => a.json()).then(json => {
        this.skills = json;
      }),
      fetch('websites.json').then(a => a.json()).then(json => {
        this.websites = json;
      })
  },
  data() {
    return {
      zeroniIcons: [],
      skills: [],
      websites: []
    }
  },
  methods: {
    // generated by copilot
    openWebsite(link) {
      window.open(link, '_blank');
    },
    closeWebsiteShowcase() {
      const showcase = document.getElementById('websiteShowcase');
      showcase.classList.add('d-none');
      const miniSite = document.getElementById('miniSite');
      miniSite.classList.remove('d-none');
//from copilot, modified by me
      // hide all projects
      this.websites.forEach(p => {
        const el = document.getElementById(p.site);
        if (el) el.classList.add('d-none');
      });
    },
    openWebsiteShowcase(site) {
  const showcase = document.getElementById('websiteShowcase');
  showcase.classList.remove('d-none');

  const miniSite = document.getElementById('miniSite');
  miniSite.classList.add('d-none');
//from chatgpt, modified by me
  // hide all projects first
  this.websites.forEach(p => {
    const el = document.getElementById(p.site);
    if (el) el.classList.add('d-none');
  });

  // show selected project
  const project = this.websites.find(p => p.site === site);

  if (project) {
    const projectElement = document.getElementById(project.site);
    projectElement.classList.remove('d-none');
  }
}
   }
})

app.mount('#app')