//modal code from boostrap. will implement vue later
const myModal = document.getElementById('myModal')
const myInput = document.getElementById('myInput')

// myModal.addEventListener('shown.bs.modal', () => {
//   myInput.focus()
// })


const app = Vue.createApp({
  created() { 
    fetch('zeronis.json').then(rep => rep.json()).then(json => {
      this.zeroniIcons = json;
    }),
      fetch('skills.json').then(a => a.json()).then(json => {
        this.skills = json;
      }),
      fetch('websites.json').then(a => a.json()).then(json => {
        this.websites = json;
      })
      fetch('journey.json').then(a => a.json()).then(json => {
        this.journeys = json;
      })
  },
  data() {
    return {
      zeroniIcons: [],
      skills: [],
      websites: [],
      journeys: [],
      currentRange: 0,
      currentSection: 'web' // default selected (from chatgpt, modified by me)
    }
  },
  methods: {
    // generated by copilot
    openWebsite(link) {
      window.open(link, '_blank');
    },
    closeWebsiteShowcase() {
      const showcase = document.getElementById('websiteShowcase');
      showcase.classList.add('d-none');
      const miniSite = document.getElementById('miniSite');
      miniSite.classList.remove('d-none');
//from copilot, modified by me
      // hide all projects
      this.websites.forEach(p => {
        const el = document.getElementById(p.site);//p.site is the id of the project element in the HTML
        if (el) el.classList.add('d-none');//if the element exists, add the 'd-none' class to hide it
      });
    },
    openWebsiteShowcase(site) {
  const showcase = document.getElementById('websiteShowcase');
  showcase.classList.remove('d-none');

  const miniSite = document.getElementById('miniSite');
  miniSite.classList.add('d-none');
//from chatgpt, modified by me
  // hide all projects first
  this.websites.forEach(p => {
    const el = document.getElementById(p.site);//p.site is the id of the project element in the HTML
    if (el) el.classList.add('d-none');//if the element exists, add the 'd-none' class to hide it
  });

  // show selected project
  const project = this.websites.find(p => p.site === site); //find the project in the websites array that matches the selected site
  if (project) {
    const projectElement = document.getElementById(project.site); //get the element of the selected project using its id
    projectElement.classList.remove('d-none');//remove the 'd-none' class to show the selected project
  }
}
  },
  //from Shagan Sangha
  directives: {
    'fade-on-scroll': {
      mounted(el) { //the element's styles are put on it to happen upon load
        el.style.opacity = '0';
        el.style.transform = 'translateY(40px)';
        el.style.transition = 'opacity 0.8s ease-out, transform 0.8s ease-out';

        const observer = new IntersectionObserver(([entry]) => { //observes for user scrolling upon said element
          if (entry.isIntersecting) {
            el.style.opacity = '1';//make these styles apply if user scrolled upon element
            el.style.transform = 'translateY(0)'; //make these styles apply if user scrolled upon element
            observer.unobserve(el); //leave element alone after, making it not fade-in again and again
          }
        }, { threshold: 0.1 }); //how much a user needs to scroll to the element's location for fade-in to occur

        observer.observe(el); //observe the next element w/ class 'fade-on-scroll'
      }
    }
  },
  computed: {
    //generated by chatgpt, modified by me
  sliderStyle() {
// Calculate the percentage based on the current range and total journeys
    const percentage =
      (this.currentRange / (this.journeys.length - 1)) * 100; //this.journeys.length - 1 because the range starts at 0, so we need to subtract 1 to get the correct percentage
// Return the style object for the slider background
    return {
      background: `linear-gradient(
        to right,
        #A9D6FF 0%,
        #A9D6FF ${percentage}%,
        #E5E7EB ${percentage}%,
        #E5E7EB 100%
      )`
    }; //the first color is the filled portion, the second color is the unfilled portion
  }
}
})

app.mount('#app')